import nextConfig from 'eslint-config-next/core-web-vitals'
import tsConfig from 'eslint-config-next/typescript'

/**
 * Every folder under `src/` publishes its public surface through an `index.ts`
 * barrel, so a deep import into one is an error rather than a convention. Delete
 * the `no-restricted-imports` block below if your project prefers direct imports.
 */
const BARREL_MESSAGE =
  'Import from the folder barrel (e.g. @/lib, @/components/ui) instead of an internal file. ' +
  'See docs/architecture/conventions.md.'

const eslintConfig = [
  // Global ignores (replaces the deprecated .eslintignore).
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'build/**',
      'dist/**',
      'coverage/**',
      'public/**',
      'tmp/**',
      'site/**', // MkDocs build output
      'test-results/**', // Playwright
      'playwright-report/**', // Playwright
      'blob-report/**', // Playwright
      'next-env.d.ts', // generated by Next.js
      '.vercel/**',
    ],
  },
  ...nextConfig,
  ...tsConfig,
  {
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['@/lib/*'], message: BARREL_MESSAGE },
            { group: ['@/components/ui/*'], message: BARREL_MESSAGE },
            { group: ['@/components/layout/*'], message: BARREL_MESSAGE },
            { group: ['@/config/*/*'], message: BARREL_MESSAGE },
          ],
        },
      ],
    },
  },
  {
    files: ['tests/**/*.{ts,tsx}'],
    rules: {
      // Specs import the module under test directly by design; the barrel
      // convention applies to application code only.
      'no-restricted-imports': 'off',
      // Mocks for next/image legitimately render bare <img> elements.
      '@next/next/no-img-element': 'off',
      'jsx-a11y/alt-text': 'off',
      // Mocks declare unused params prefixed with `_` on purpose.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', destructuredArrayIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['*.config.{ts,mjs}', 'next.config.ts'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
]

export default eslintConfig
